<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_add</name>
   <tag></tag>
   <elementGuidId>336563ad-53e4-4d66-ae12-6e233cc77941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'fake-form-text-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>html.js.no-device.placeholder.cors.svg.no-touchevents.csstransforms.csstransitions.borderradius.cssvhunit.backgroundsize.csspositionsticky.cssgradients.rgba.no-cssscrollbar.mediaqueries.boxshadow.objectfit.object-fit.opacity.flexbox body.eurail-responsive.html.not-front.not-logged-in.no-sidebars.page-checkout.page-checkout-.page-checkout-9927861.domain-www-interrail-eu.i18n-en.scroll-down-processed.scroll-to-processed.jquery-once-2-processed.jquery-once-4-processed.eurail-breakpoint-handler-processed.ready-panels.ready-panel-cart.errors_form_gtm-processed.ready div.page.eurail-widget-dropdown-controller-processed.eurail-dialog-trigger-processed div.page-content form#commerce-checkout-form-checkout.hideSubmitButton-processed div.wrapper main.main-content article.block.block-checkout.block-cart.eurail-blockСheckout-processed.jquery-once-2-processed div.container section.checkout-section div.section-body section.checkout-subsection div.subsection-body div.form-item.form-type-textfield.form-item-customer-profile-traveler-field-translated-ml-starting-date1.form-type-textfield-a.form-type-textfield-datepicker.eurail-form-item-text-processed.eurail-form-item-datepicker-processed.is-pikaday-initialized span.fake-form-text span.fake-form-text-value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[1]/form/div/main/article/div/section[1]/div/section/div/div[1]/span/span[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fake-form-text-value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-customer-profile-traveler-field-translated-ml-starting-date1</value>
   </webElementProperties>
</WebElementEntity>
