<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Croatha</name>
   <tag></tag>
   <elementGuidId>7bbb2811-743e-4e66-b0b8-aadb505ae29a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;edit-commerce-shipping-field-country-and-speed--3&quot;]/option[12]</value>
   </webElementProperties>
</WebElementEntity>
