<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1527164945262</name>
   <tag></tag>
   <elementGuidId>61996a7a-0591-4b00-9ad0-29ba04b1a3c8</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;commerce-checkout-form-checkout&quot;]/div/main/article/div/section/div/section/div/div[1]/span/span[1]</value>
   </webElementProperties>
</WebElementEntity>
