<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mr</name>
   <tag></tag>
   <elementGuidId>5214a211-4b1f-44e1-a078-97b77bd48819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div[1]/form/div/main/article/div/section[1]/div/section/div/div[3]/div/div[1]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[1]/form/div/main/article/div/section[1]/div/section/div/div[3]/div/div[1]/span/span</value>
   </webElementProperties>
</WebElementEntity>
