<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_fake-form-text-value</name>
   <tag></tag>
   <elementGuidId>0dc3d7df-f3e9-4c39-a19c-668d04c65978</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fake-form-text-value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commerce-checkout-form-checkout&quot;)/div[@class=&quot;wrapper&quot;]/main[@class=&quot;main-content&quot;]/article[@class=&quot;block block-checkout block-cart eurail-blockСheckout-processed jquery-once-2-processed&quot;]/div[@class=&quot;container&quot;]/section[@class=&quot;checkout-section&quot;]/div[@class=&quot;section-body&quot;]/section[@class=&quot;checkout-subsection&quot;]/div[@class=&quot;subsection-body&quot;]/div[@class=&quot;form-item form-type-textfield form-item-customer-profile-traveler-field-translated-ml-starting-date1 form-type-textfield-a form-type-textfield-datepicker eurail-form-item-text-processed eurail-form-item-datepicker-processed is-pikaday-initialized&quot;]/span[@class=&quot;fake-form-text&quot;]/span[@class=&quot;fake-form-text-value&quot;]</value>
   </webElementProperties>
</WebElementEntity>
