<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SEE ITALY PASS PRICES</name>
   <tag></tag>
   <elementGuidId>6b7e2c2d-a275-4fc3-a35a-59d19dd9dc79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div[1]/div[1]/div/div/div[12]/div/div/div/div/div[2]/div/div/div/div/p[5]/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href=&quot;https://www.interrail.eu/en/interrail-passes/one-country-pass/italy-passes/italy&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-resp-orange</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.interrail.eu/en/interrail-passes/one-country-pass/italy-passes/italy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEE ITALY PASS PRICES</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[1]/div[1]/div/div/div[12]/div/div/div/div/div[2]/div/div/div/div/p[5]/a</value>
   </webElementProperties>
</WebElementEntity>
